### PR TITLE
Large video preview

### PR DESCRIPTION
**Pull request by nathanshammah**
Make the larger video preview embedded. 

Basically from this: 

small embed

to this: 
large-yt-embed

Besides personal taste, I think this way one may not leave the UF website.

### CODE REVIEW

**Comment by crazy4pi314** [comment]
The reason I originally made the previews smaller is because it didn't scale at all on mobile. So if you tried scrolling you would inadvertently play the video as it would take up most of the screen. It seems to be surprisingly tricky to get the iframes to auto scale correctly (though I am not a webdev), if you have any suggestions let me know. I would very minorly oppose making them bigger so that the website is still useable on mobile.

**Comment by crazy4pi314** [comment]
Also previewing the calendar, we have the same issue on mobile with that iframe too...

**Comment by nathanshammah** [comment]
@crazy4pi314 I did think of that, but did not know how to test it, and now remember that you mentioned it. Maybe this does it: https://coolestguidesontheplanet.com/videodrome/youtube/

**Comment by crazy4pi314** [comment]
@nathanshammah you can always test mobile previews by right-clicking on a page anywhere in a browser and picking the inspect option. There should be settings there (varies by browser) that let you pick specific phone models to test how the website would look there.

I have tried solutions like that (just tried this one locally to verify) but it doesn't seem to work. There seems to be some fixed size override if you try to scale the video relative to the page. If you give other explicit numbers it works. I'll keep looking.

**Pull request closed without merging**
