### PR TITLE
Adding shop section to website

### PR DESCRIPTION
**Pull request by crazy4pi314**
From previous discussions, the merch store is now just a sidebar link and there is a note on the donate page based on Nathan's suggestion

### CODE REVIEW

**Review by nathanshammah — DISMISSED** [review]
I tested it locally and it works fine. Personally I don't like too much the word "merch".It sounded quite specific jargon. Maybe it's just me. Alternatives: shop, store, swag (also jargon, but quite popular), clothes, t-shirts.

**Review by willzeng — CHANGES_REQUESTED** [review]
I agree with @nathanshammah's suggestion. Would prefer "shop" to "merch" as it's clearer globally.

Other than this small thing, look great and am excited to have it up! Well done @crazy4pi314

**Comment by crazy4pi314** [comment]
I looked at the couple bigger changes, and the two quarterly updates just got whitespace linted, and the navigation was actually broken from the sidebar on the 2020 annual review. It looks like it was copied from the root directory and not modified to reflect the post location in the hierarchy.

**Review by nathanshammah — APPROVED** [review]
LGTM, thanks @crazy4pi314.

**Comment by willzeng** [comment]
Few remaining small things:

- Linting introduced a bit funky spacing in the citations of the Q2 blog post:
image
- Q1 and Q2 blog posts seem to be missing unitaryhack on the menu
- The new QuTiP and mitiq paper update will need to have Shop added to their menus

**Comment by nathanshammah** [comment]
@crazy4pi314 if we fix these small typos we could announce the shop section. Also since we have some momentum from UH, e.g., https://twitter.com/unitaryfund/status/1422568712612294658

**Comment by crazy4pi314** [comment]
@willzeng @nathanshammah addressed these issues, should be rtg!

**Pull request merged**
