### PR TITLE
Split site into pages

### PR DESCRIPTION
**Pull request by prakhary1912**

### CODE REVIEW

**Comment by willzeng** [comment]
Thanks @prakhary1912! This looks great. Couple of quick questions:

[1] Images aren't loading in my local preview and I'm not sure why.

[2] When the hamburger collapses it overlaps the header text:
image
Perhaps in this case we could drop the subtitle "Because evolution is unitary" into the lower line?

Thanks!

**Comment by amirebrahimi** [comment]
Any chance we can get that tagline on a tee shirt? I'd buy one :)

**Comment by prakhary1912** [comment]
> Thanks @prakhary1912! This looks great. Couple of quick questions:
> 
> [1] Images aren't loading in my local preview and I'm not sure why.
> 
> [2] When the hamburger collapses it overlaps the header text:
> image
> Perhaps in this case we could drop the subtitle "Because evolution is unitary" into the lower line?
> 
> Thanks!

1. Images aren't loading because the image paths are absolute, so wouldn't work without a server. If you boot up a local server with root at `index.html`, the images will work fine.
2. Once the image loads, the tagline will fall into place.

**Comment by willzeng** [comment]
@amirebrahimi Shopify shirts for a future PR :)

**Review by willzeng — APPROVED** [review]

**Pull request merged**
