### PR TITLE
Social icons

### PR DESCRIPTION
**Pull request by crazy4pi314**
I wanted to make it easier for folks to find us other places on the web, and have used a minimal row of icons from fontawesome in the menu. It works great on web, but I can't get the css just right for the mobile view. If anyone is good at that and could help I'd appreciate it!

### CODE REVIEW

**Comment by willzeng** [comment]
@crazy4pi314 I know you're looking at a potential framework upgrade for the site. Should we still look at this PR or perhaps wait for that?

**Comment by crazy4pi314** [comment]
This should address having links for discord @willzeng, there are now social icons in desktop menu and for all views of pages in the footer.

**Review by nathanshammah — APPROVED** [review]
Checked out this branch locally, the icons look great. Before the last commits I had two menus, it kept the mobile one, now is fixed and very neat with the yellow highlight. Thanks @crazy4pi314.

**Comment by willzeng** [comment]
These look great @crazy4pi314! They aren't on the blog pages but we can add those later. I'll merge these in the meantime

**Comment by crazy4pi314** [comment]
They aren't on the blog pages? I did a ctl f for all the header/footer stuff and inspected a few but I guess there were more... More evidence for a ssg 😊 ( I was frustrated again by this yesterday and got most of the infra and content done for a hugo based page you can see in private repos)

**Comment by willzeng** [comment]
Very cool. Looking forward to our new ssg future :)

**Pull request merged**
