### PR TITLE
Adding Donate as a menu item

### PR DESCRIPTION
**Pull request by crazy4pi314**
For giving Tuesday, @nathanshammah suggested we add donate as a menu item to the site. This does so and directly links it to the paypal portal.

### CODE REVIEW

**Review by nathanshammah — CHANGES_REQUESTED** [review]
Thanks @crazy4pi314. I think the button needs to be added also to the `posts/` pages for consistency. By the way, noticed that we miss the talks button too in the posts. 

In #53 I was suggesting to add a page, because this way we could link to a proper unitary.fund/donate. As a temporary fix this works too. 

(By the way this duplication of work on all pages is pretty annoying, I agree that if we found a way to simplify edits, that would be great. Something like a single "menu" page, but I am too ignorant about html. Also going beyond raw html edit may simplify things)

**Comment by crazy4pi314** [comment]
I have updated it with a separate page:
**Mobile:**
image
**Web:**
image

**Comment by crazy4pi314** [comment]
>(By the way this duplication of work on all pages is pretty annoying, I agree that if we found a way to simplify edits, that would be great. Something like a single "menu" page, but I am too ignorant about html. Also going beyond raw html edit may simplify things)

Yeah, this is really cumbersome, and I will look into porting to Jekyll or Hugo. I have used both extensively and make editing a page like this as simple as editing a markdown readme 💖

**Review by nathanshammah — APPROVED** [review]
Thanks @crazy4pi314!

**Pull request merged**
