### PR TITLE
Adding UF merch shop

### PR DESCRIPTION
**Pull request by crazy4pi314**
Added to sidebar and has an immediate redirect link to the spreadshirt shop.

### CODE REVIEW

**Comment by willzeng** [comment]
@crazy4pi314 I like the look of the shop page! Why is the shop.html page needed if it just redirects? Could we not directly link to https://shop.spreadshirt.com/unitaryfund ?

**Comment by crazy4pi314** [comment]
Heh thats a good point. I initially tried to embed it on our site, I'll just setup the sidebar to link directly.

**Comment by willzeng** [comment]
@crazy4pi314 This looks good to me. Is the backend for us to receive payments set up? If it is then I think we can merge this

**Comment by crazy4pi314** [comment]
It seems like this was already updated, closing.

**Pull request closed without merging**
