### PR TITLE
Add md file for blog post about quantum volume

### PR DESCRIPTION
**Pull request by nickdgardner**

### CODE REVIEW

**Review by nathanshammah — COMMENTED** [review]
Hi @nickdgardner, sorry for the slow reply, just want to say that it looks great to me. We'll schedule the post from next week.

**Review by nathanshammah — CHANGES_REQUESTED** [review]
Thanks @nickdgardner. 
Two small requests:
- Please generate the html page, using the pandoc commands reported in the [readme](https://github.com/unitaryfund/unitary-fund#writing-a-blog-post).
- Please add a link to the html page to the blog index, blog.html. 

Also, please have a double check at the html file locally to check that pandoc converted it correctly, e.g., #243.

- I would personally cite the framework through which this addition was created, which is the CS59SI course at Stanford (Nyle and Zhaoyi could be mentioned, or the fact that three students were involved). One could include a [link](https://bulletin.stanford.edu/courses/2232631) to the course. 
- It would be nice to add a picture. UF can support with this for the last polish.

**Comment by nickdgardner** [comment]
@nathanshammah Hey, sorry I was just about to finish this up. I see that the PR was merged already and the blog post is up. Thanks for taking care of the last details! I'm happy to (1) provide a picture, and (2) mention Nyle and Zhaoyi names at the end of the post. Can I still do either/both of those things, or is it more hassle than it's worth?

**Comment by andreamari** [comment]
Hi @nickdgardner, @nathanshammah is on vacation in this period. But feel free to open a new PR to apply minor changes on the merged blog post.

**Pull request merged**
